services:
    whatsapp-redis:
        image: redis:7
        command: redis-server --port 7777
        ports:
            - "7777:7777"
        healthcheck:
            test: redis-cli -p 7777 ping
            interval: 5s
            timeout: 10s
            retries: 10
        